### PR TITLE
setup dependabot for testing

### PR DESCRIPTION
**Pull request by fscherf**
We had some problems with version ranges in test dependencies, so @maratori recommended using dependabot.
This PR splits all dependencies in dedicated files and and pins all versions.

@sobolevn: I enabled "Dependabot alerts" and "Dependabot security updates" in the project settings. Is there more i have to do to make dependabot work like expected?

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Hi!

You can also add `.github/dependabot.yml` file. Like so: https://github.com/wemake-services/wemake-python-package/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.github/dependabot.yml

You might need to add multiple entries with different `directory setting, like: tests/REQUIREMENTS.lint.txt`. One for each `REQUIREMENTS.*` file

Note that it also includes github-actions update.

**Comment by fscherf** [comment]
@sobolevn Thanks for the example! I added a dependabot config. I assume the github-actions sections checks all configs in ``.github``. Is that correct?

**Review by sobolevn — APPROVED** [review]
Great! Thanks!

**Comment by fscherf** [comment]
@sobolevn Great! Thanks for reviewing! :)

**Pull request merged**
