### PR TITLE
Update writing-a-lona-form.rst

### PR DESCRIPTION
**Pull request by chlor**
doc: cookbook: writing a Lona form: fix syntax error)

### CODE REVIEW

**Comment by fscherf** [comment]
Hi @chlor!
Thanks for this fix. Could you prefix your commit message to something like this: `doc: cookbook: wirting a Lona form: fix syntax error`? Besides that, the patch looks ok to me

**Comment by chlor** [comment]
done

**Comment by fscherf** [comment]
> done

Did you push? I only see the old commit

**Comment by fscherf** [comment]
@chlor: I updated your commit message without changing the patch itself. When the ci is happy, i will merge this pr

**Comment by fscherf** [comment]
@chlor: Your change is now live on http://lona-web.org
Thanks for contributing! :)

**Pull request merged**
