### PR TITLE
lint: use flake8-bugbear plugin

### PR DESCRIPTION
**Pull request by maratori**
See https://github.com/PyCQA/flake8-bugbear

### CODE REVIEW

**Comment by fscherf** [comment]
@maratori this list of plugins gets pretty long. I have no experience with most of them. Are you willing to maintain this list? Or maybe linting as whole?

**Comment by maratori** [comment]
@fscherf sure, I can maintain them.
I'm not an expert in python linters either (yet :)
However I have a lot of experience with linters in golang.

I add only linters with minimal impact. Most probably we will not have any problems with them.

**Comment by fscherf** [comment]
@maratori cool :) Then i am ok with all the plugins :)

**Comment by fscherf** [comment]
@maratori: Why do you add variables with leading underscore in some hunks, and remove it in others?

**Comment by maratori** [comment]
@fscherf Good question. I no answer :)
I reverted unnecessary changes.
Underscore in variable name stresses that it is not used.

**Comment by fscherf** [comment]
@maratori Looks much cleaner now :) Thanks!

**Pull request merged**
