### PR TITLE
Fixes coverage

### PR DESCRIPTION
**Pull request by sobolevn**
Refs #18 
Refs #16

### CODE REVIEW

**Comment by sobolevn** [comment]
It is strange, that this message appears to be empty. Inside the build logs it says:

```
Run codecov/codecov-action@v2
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (3094f05b76925427642be5d4bbde7fba202c82aab2b7d31fd32620d735b3be47  codecov)
/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov -n  -Q github-action-2.0.2 -f ./coverage.xml -C 57357d90a2df57d540c18687b84c71724385ea1b
[2021-08-21T15:52:46.158Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.1.0
[2021-08-21T15:52:46.166Z] ['info'] => Project root located at: /home/runner/work/lona/lona
[2021-08-21T15:52:46.167Z] ['info'] -> No token specified or token is empty
[2021-08-21T15:52:46.186Z] ['info'] Searching for coverage files...
[2021-08-21T15:52:46.200Z] ['info'] => Found 1 possible coverage files:
  ./coverage.xml
[2021-08-21T15:52:46.201Z] ['info'] Processing ./coverage.xml...
[2021-08-21T15:52:46.207Z] ['info'] Detected GitHub Actions as the CI provider.
[2021-08-21T15:52:46.207Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.0.2-uploader-0.1.0&token=*******&branch=patch-1&build=1153900990&build_url=https%3A%2F%2Fgithub.com%2Flona-web-org%2Flona%2Factions%2Fruns%2F1153900990&commit=57357d90a2df57d540c18687b84c71724385ea1b&job=test&pr=19&service=github-actions&slug=lona-web-org/lona&name=&tag=&flags=&parent=
[2021-08-21T15:52:46.587Z] ['info'] Uploading...
[2021-08-21T15:52:46.721Z] ['info'] {"status":"success","resultURL":"https://codecov.io/github/lona-web-org/lona/commit/57357d90a2df57d540c18687b84c71724385ea1b"}
```

Link: https://github.com/lona-web-org/lona/pull/19/checks?check_run_id=3389802289#step:6:1

**Comment by sobolevn** [comment]
I am pretty sure that you have to click "create/import project" on their website to fix it.

**Comment by fscherf** [comment]
https://app.codecov.io/gh/lona-web-org/lona is available now, but the page says 

```
Let's get your project covered.

No repository activation required. Simply upload a report and the project activates automatically.

STEP 1 - COPY TOKEN
...

```

**Comment by sobolevn** [comment]
That's what I see:
Снимок экрана 2021-08-21 в 22 36 58

Try to merge this PR, let's see what happens.

**Comment by fscherf** [comment]
@sobolevn: Ahhhh! I had to press "Reset GithHub Webhooks"! Now it seems to be working :)
Thanks! You helped a lot! :)

**Pull request merged**
