### PR TITLE
Fix `dependabot.yml` to work with dev deps

### PR DESCRIPTION
**Pull request by sobolevn**
As you can see, your dependecies are not updated.
Dependabot expects relative paths, not absolute ones.

### CODE REVIEW

**Comment by fscherf** [comment]
@sobolevn: Great! Thanks :)

**Comment by fscherf** [comment]
@sobolevn: dependabot opened 22 pull-requests since this pull-request is merged. Is this wanted behavior?

**Comment by sobolevn** [comment]
Yes, because we have a lot of outdated deps 🙂

**Comment by fscherf** [comment]
Fair enough :D 
Do you have any recommendations on how to merge the prs, fix those which break the test suite and which order to choose? 
For example: can i just merge all prs where the checks are green?

**Pull request merged**
