### PR TITLE
Switches to GitHub Actions

### LINKED ISSUE #14: Your CI does not work
It is broken since the repo was moved to this org:
Снимок экрана 2021-08-21 в 10 41 28

Also, coverage is not found:
Снимок экрана 2021-08-21 в 10 41 58

### LINKED ISSUE #15: Python3.9 support
I am going to add `python3.9` test env as a part of #14 

I hope, that it will work (it works most of the times).

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #14 
Closes #15

### CODE REVIEW

**Comment by fscherf** [comment]
Wow great! I there any way to test this before merging? (i suspect no :D )

**Comment by sobolevn** [comment]
I don't think so 😞 
But, I promise to fix any issues that will reveal themself after the merging is done!

**Comment by fscherf** [comment]
I take your work for it! :D 
Do i need to configure something using the web interface?

**Comment by sobolevn** [comment]
Nope, it should be fine as-is

**Comment by sobolevn** [comment]
Looks like it works! https://github.com/lona-web-org/lona/actions/runs/1153482025
:tada:

**Comment by fscherf** [comment]
@sobolevn: whoooop! :)) I can remove the travis badge than.
Thank you! I fiddled with this problem since the move to the new organization. Do you want some stickers for your work? :)

https://www.reddit.com/r/lona_web_org/comments/p5i7ch/we_got_stickers/

**Comment by sobolevn** [comment]
Sure! I love stickers! What are the next steps? 🙂

**Comment by fscherf** [comment]
DM me on reddit or send me a mail to f.scherf@pengutronix.de :)

**Comment by fscherf** [comment]
@sobolevn codecov still seems to don't work but the organization showed up in the codecov webinterface. I think i need to set a environment variable with a secret from codecov. Where in the github action config would i set such an variable?

**Comment by sobolevn** [comment]
@fscherf no, you don't have to set any variables. I don't do this. But, you possible have to go to your `codecov` account and add this project from GitHub.

**Pull request merged**
