### PR TITLE
Proofreading

### PR DESCRIPTION
**Pull request by hut**
This PR fixes some typos and wording in the tutorial chapters 6-11.

### CODE REVIEW

**Comment by fscherf** [comment]
@hut: great PR, thanks for that! There is only one piece of wording, i am not to sure about

**Comment by hut** [comment]
Added a commit where I rephrased a note that was confusing to me.

**Comment by fscherf** [comment]
> Added a commit where I rephrased a note that was confusing to me.

Nice! The new paragraph is much clearer.

**Review by fscherf — CHANGES_REQUESTED** [review]

**Comment by fscherf** [comment]
@hut: Thanks for these changes :)

**Review by fscherf — APPROVED** [review]

**Pull request merged**
