### PR TITLE
html: parsing: pass attributes to constructor

### PR DESCRIPTION
**Pull request by maratori**
It will allow to add some validation/conversion inside node constructor.
The only downside - all nodes must accept `attributes` or `kwargs` in constructor.

### CODE REVIEW

**Comment by maratori** [comment]
@fscherf What do you think?

**Comment by fscherf** [comment]
@maratori To be honest: I don't completely understand what You are doing and why this is necessary. Is this infrastructure to fix something for future use?

**Comment by maratori** [comment]
@fscherf I decided that proposed solution is not good enough. Closing PR.
I'll create a discussion about parsing html.

**Comment by fscherf** [comment]
@maratori Ok! I am looking forward towards it. Thanks for Your time :)

**Comment by maratori** [comment]
Just a quick update. I decided that current solution is OK and I will not create a discussion.
Sorry for distraction.

**Pull request closed without merging**
